[project]
name = "ChessIntelligenceSystem"
version = "0.0.1"
description = "多棋类AI推理与训练系统，基于PyTorch，支持标准化HTTP API。"
authors = [
    {name = "Yee Cube", email = "yee.cube@example.com"}
]
requires-python = ">=3.10"
dependencies = [
    "torch",
    "numpy",
    "scipy",
    "pandas",
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-multipart",
    "aiofiles",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    # pytest anyio 支持
    "anyio",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"